export enum ActionType {
    FETCH_IMAGES = "FETCH_IMAGES",
    FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS",
    FETCH_IMAGES_ERROR = "FETCH_IMAGES_ERROR",
    FETCH_IMAGE_DETAILS = "FETCH_IMAGE_DETAILS",
    FETCH_IMAGE_DETAILS_SUCCESS = "FETCH_IMAGE_DETAILS_SUCCESS",
    FETCH_IMAGE_DETAILS_ERROR = "FETCH_IMAGE_DETAILS_ERROR",
}